//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATranquilinoAeroMexicoEntities : DbContext
    {
        public ATranquilinoAeroMexicoEntities()
            : base("name=ATranquilinoAeroMexicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pasajero> Pasajeroes { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
        public virtual DbSet<VueloPasajero> VueloPasajeroes { get; set; }
    
        public virtual ObjectResult<VueloGetAll_Result> VueloGetAll(string fechaInicio, string fechaFin)
        {
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetAll_Result>("VueloGetAll", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<PasajeroGetAll_Result> PasajeroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasajeroGetAll_Result>("PasajeroGetAll");
        }
    
        public virtual int VueloReservacion(string vueloNumero, Nullable<int> idPasajero)
        {
            var vueloNumeroParameter = vueloNumero != null ?
                new ObjectParameter("VueloNumero", vueloNumero) :
                new ObjectParameter("VueloNumero", typeof(string));
    
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VueloReservacion", vueloNumeroParameter, idPasajeroParameter);
        }
    
        public virtual ObjectResult<VueloGetByIdPasajero_Result> VueloGetByIdPasajero(Nullable<int> idPasajero)
        {
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetByIdPasajero_Result>("VueloGetByIdPasajero", idPasajeroParameter);
        }
    
        public virtual ObjectResult<VueloGetByIdPasajero2_Result> VueloGetByIdPasajero2(Nullable<int> idPasajero)
        {
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetByIdPasajero2_Result>("VueloGetByIdPasajero2", idPasajeroParameter);
        }
    
        public virtual ObjectResult<VueloGetNoAsignado_Result> VueloGetNoAsignado(Nullable<int> idPasajero)
        {
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetNoAsignado_Result>("VueloGetNoAsignado", idPasajeroParameter);
        }
    
        public virtual int ReservacionAdd(string numeroVuelo, Nullable<int> idPasajero)
        {
            var numeroVueloParameter = numeroVuelo != null ?
                new ObjectParameter("NumeroVuelo", numeroVuelo) :
                new ObjectParameter("NumeroVuelo", typeof(string));
    
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReservacionAdd", numeroVueloParameter, idPasajeroParameter);
        }
    
        public virtual int PasajeroAdd(string nombres, string apellidos)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PasajeroAdd", nombresParameter, apellidosParameter);
        }
    }
}
